services:
  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ./log:/app/log
    # command: ["reqarg1", "--optional-arg", "optarg1"]
    command: ["gnaf.parquet"]

  tests:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: ["uv", "run", "pytest", "-q", "-vv"]
